name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout --progress  gh-pages refs/remotes/origin/gh-pages
        cp ./dist/* ./
        git add .
        git commit -m "Updating GH Pages"
        git push