name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - name: Push Compiled
      uses: actions-x/commit@v2
      with:
        email: shmueli.yosef@englard.net
        name: Shmueli Englard (Bot)
        branch: gh-pages
        files: dist/*
        token: ${{ secrets.GITHUBACCESSTOKEN }}
