# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - uses: igolopolosov/github-action-release-github-pages@v1
    - name: Release GitHub Pages
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUBACCESSTOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: samuelenglard
        GITHUB_PAGES_REPO_NAME: shmuelie.englard.net
        GITHUB_PAGES_RELEASE_BRANCH: gh-pages
        PROJECT_BUILD_FOLDER: dist
